# Generated by Django 5.2.5 on 2026-07-03 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('calon_mahasiswa', 'Calon Mahasiswa'), ('admin_pmb', 'Admin PMB'), ('super_admin', 'Super Admin')], default='calon_mahasiswa', max_length=20)),
                ('nik', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='NIK')),
                ('nisn', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NISN')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
            },
        ),
    ]
