# Generated by Django 5.2.5 on 2026-07-03 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=150, verbose_name='Nama Kegiatan')),
                ('tanggal_mulai', models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
            ],
            options={
                'verbose_name': 'Jadwal Penting',
                'verbose_name_plural': 'Jadwal Penting',
                'ordering': ['tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='JalurMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jalur', models.CharField(max_length=50, verbose_name='Nama Jalur')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('periode_mulai', models.DateField(blank=True, null=True, verbose_name='Periode Mulai')),
                ('periode_selesai', models.DateField(blank=True, null=True, verbose_name='Periode Selesai')),
            ],
            options={
                'verbose_name': 'Jalur Masuk',
                'verbose_name_plural': 'Jalur Masuk',
                'ordering': ['periode_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(max_length=100, verbose_name='Nama Jurusan')),
                ('akreditasi', models.CharField(blank=True, max_length=10, verbose_name='Akreditasi')),
                ('kuota', models.PositiveIntegerField(default=0, verbose_name='Kuota Utama')),
                ('kuota_cadangan', models.PositiveIntegerField(default=0, verbose_name='Kuota Cadangan')),
            ],
            options={
                'verbose_name': 'Jurusan',
                'verbose_name_plural': 'Jurusan',
                'ordering': ['nama_jurusan'],
            },
        ),
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_registrasi', models.CharField(max_length=20, unique=True, verbose_name='No. Registrasi')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='NIK')),
                ('nisn', models.CharField(max_length=10, unique=True, verbose_name='NISN')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('no_hp', models.CharField(blank=True, max_length=15, verbose_name='No. HP')),
                ('asal_sekolah', models.CharField(blank=True, max_length=150, verbose_name='Asal Sekolah')),
                ('nilai_akademik', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nilai Akademik')),
                ('nilai_tes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nilai Tes')),
                ('skor_akhir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Skor Akhir')),
                ('status_seleksi', models.CharField(choices=[('menunggu', 'Menunggu'), ('lulus', 'Lulus'), ('cadangan', 'Cadangan'), ('tidak_lulus', 'Tidak Lulus')], default='menunggu', max_length=20, verbose_name='Status Seleksi')),
                ('status_bayar', models.CharField(choices=[('belum_lunas', 'Belum Lunas'), ('lunas', 'Lunas')], default='belum_lunas', max_length=15, verbose_name='Status Pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Daftar')),
                ('jalur_masuk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendaftar', to='pendaftaran.jalurmasuk', verbose_name='Jalur Masuk')),
                ('jurusan_pilihan1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendaftar_pilihan1', to='pendaftaran.jurusan', verbose_name='Jurusan Pilihan 1')),
                ('jurusan_pilihan2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendaftar_pilihan2', to='pendaftaran.jurusan', verbose_name='Jurusan Pilihan 2')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftar', to=settings.AUTH_USER_MODEL, verbose_name='Akun User')),
            ],
            options={
                'verbose_name': 'Pendaftar',
                'verbose_name_plural': 'Pendaftar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_dokumen', models.CharField(choices=[('ktp', 'KTP / Kartu Identitas'), ('kk', 'Kartu Keluarga'), ('pas_foto', 'Pas Foto'), ('ijazah', 'Ijazah / SKL')], max_length=30, verbose_name='Jenis Dokumen')),
                ('file', models.FileField(upload_to='dokumen/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='File Dokumen')),
                ('status_verifikasi', models.CharField(choices=[('belum_diverifikasi', 'Belum Diverifikasi'), ('terverifikasi', 'Terverifikasi'), ('ditolak', 'Ditolak')], default='belum_diverifikasi', max_length=20, verbose_name='Status Verifikasi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Upload')),
                ('pendaftar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pendaftaran.pendaftar', verbose_name='Pendaftar')),
            ],
            options={
                'verbose_name': 'Dokumen',
                'verbose_name_plural': 'Dokumen',
                'ordering': ['pendaftar', 'jenis_dokumen'],
            },
        ),
        migrations.AddIndex(
            model_name='pendaftar',
            index=models.Index(fields=['nisn'], name='idx_pendaftar_nisn'),
        ),
        migrations.AddIndex(
            model_name='pendaftar',
            index=models.Index(fields=['jurusan_pilihan1'], name='idx_pendaftar_jurusan1'),
        ),
        migrations.AddIndex(
            model_name='pendaftar',
            index=models.Index(fields=['status_seleksi'], name='idx_pendaftar_status'),
        ),
    ]
