# Generated by Django 4.2.30 on 2026-07-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurusan',
            name='deskripsi',
            field=models.TextField(blank=True, verbose_name='Deskripsi Singkat'),
        ),
        migrations.AddField(
            model_name='jurusan',
            name='materi_pembelajaran',
            field=models.TextField(blank=True, verbose_name='Materi Pembelajaran'),
        ),
        migrations.AddField(
            model_name='jurusan',
            name='prospek_karir',
            field=models.TextField(blank=True, verbose_name='Prospek Karir'),
        ),
    ]
