# Generated by Django 4.2.30 on 2026-07-03 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_jurusan_deskripsi_jurusan_materi_pembelajaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftar',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Aktif'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='jenis_kelas',
            field=models.CharField(choices=[('reguler', 'Kelas Reguler / Pagi'), ('karyawan', 'Kelas Karyawan / Malam')], default='reguler', max_length=20, verbose_name='Jenis Kelas'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='jurusan_sekolah',
            field=models.CharField(choices=[('IPA', 'IPA'), ('IPS', 'IPS'), ('Bahasa', 'Bahasa'), ('Kejuruan', 'Kejuruan / SMK')], default='IPA', max_length=20, verbose_name='Jurusan Sekolah'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Ayah'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='nama_ibu',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Ibu'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='no_hp_ortu',
            field=models.CharField(blank=True, max_length=15, verbose_name='No. HP Orang Tua / Wali'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='pekerjaan_ortu',
            field=models.CharField(blank=True, choices=[('pns', 'PNS / BUMN'), ('swasta', 'Karyawan Swasta'), ('wiraswasta', 'Wiraswasta / Pengusaha'), ('tni_polri', 'TNI / POLRI'), ('buruh', 'Buruh / Pekerja Lepas'), ('tani_nelayan', 'Petani / Nelayan'), ('tidak_bekerja', 'Tidak Bekerja / Pensiunan'), ('lainnya', 'Lainnya')], max_length=30, verbose_name='Pekerjaan Orang Tua / Wali'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='penghasilan_ortu',
            field=models.CharField(blank=True, choices=[('kurang_1jt', 'Kurang dari Rp 1.000.000'), ('1jt_3jt', 'Rp 1.000.000 - Rp 3.000.000'), ('3jt_5jt', 'Rp 3.000.000 - Rp 5.000.000'), ('5jt_10jt', 'Rp 5.000.000 - Rp 10.000.000'), ('lebih_10jt', 'Lebih dari Rp 10.000.000')], max_length=30, verbose_name='Penghasilan Orang Tua / Wali'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='tahun_lulus',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahun Lulus'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='jenis_dokumen',
            field=models.CharField(choices=[('ktp', 'KTP / Kartu Identitas'), ('kk', 'Kartu Keluarga'), ('pas_foto', 'Pas Foto'), ('ijazah', 'Ijazah / SKL'), ('sertifikat', 'Sertifikat Prestasi')], max_length=30, verbose_name='Jenis Dokumen'),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='nilai_akademik',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nilai Akademik (Rapor)'),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='no_hp',
            field=models.CharField(blank=True, max_length=15, verbose_name='No. HP (WhatsApp)'),
        ),
    ]
