# Generated by Django 4.2.30 on 2026-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0003_pendaftar_email_pendaftar_jenis_kelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftar',
            name='no_hp_ortu_cadangan',
            field=models.CharField(blank=True, max_length=15, verbose_name='No. HP Cadangan (Opsional)'),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='no_hp_ortu',
            field=models.CharField(blank=True, max_length=15, verbose_name='No. HP Utama Orang Tua / Wali'),
        ),
    ]
